### ISSUE TITLE
Footnote toolbar working on exhibit pages but not simple pages

### ISSUE THREAD

**Issue by akprtll** [DigitalCarleton/OmekaFootnotesJS#1]

**Comment by apjmason** [comment]
Can you provide details on what version of Omeka you’re running and what other plugins/versions you have active?

**Comment by spswanz** [comment]
Same issue for me too. Using Omeka Classic Version 2.7.1 
With these plugins active: COinS, Exhibit Builder, Simple Pages, CSV Import, Dropbox, Geolocation

**Comment by apjmason** [comment]
Thanks, we’ll check it out and push a fix ASAP

**Comment by akprtll** [comment]
Running Omeka Classic 2.6.1 here and have essentially the same plugin setup as spswanz, except without COinS active but running "Search by Metadata." Thanks!

**Comment by walshbr** [comment]
Same, on Omeka 2.7.1. My plugins are: blogger,  CSV Import, Docs Viewer, Exhibit Builder, HTML5 Media, and this one. 

FWIW, I get a console warning on both the simple pages and exhibits editing interfaces:

/omeka/application/views/scripts/javascripts/vendor/tinymce/skins/lightgray/skin.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I'm not sure it's relevant, because it persists with or without this particular plugin activated. But that appears to be an error from using an outdated version of TinyMCE, which is the library Omeka is using for their WYSIWYG editor - https://github.com/tinymce/tinymce/issues/4649. The warning/error has been fixed in later releases, but my version of Omeka, at least, shipped with 4.9.4. Was fixed in TinyMCE 5.2.1. Since that warning is related to the editor interface I thought I might raise it in case it helped you troubleshoot.

**Comment by bierleya** [comment]
We've just issued a new release [v1.1](https://github.com/DigitalCarleton/OmekaFootnotesJS/releases/tag/v1.1) that resolves this issue. Thanks!
